name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.0'
      - name: Build project
        run: |
          TAGS="remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp"
          mkdir -p web/build
          touch web/build/empty
          export CGO_ENABLED=0
          go build -tags "$TAGS" -o containerup_linux_amd64
      - name: Test upgrading
        run: |
          IMAGE=containerup:latest
          
          echo "Build image"
          podman build -t $IMAGE .

          echo "Start old container"
          PWD_HASH='$2a$10$tRhTPH7xGTJnNUUWgH/96.klhqU2z7zEPTwqa0/KfzJa4RHrVQF0O'
          SOCKET_VOLUME="${XDG_RUNTIME_DIR}/podman/podman.sock:/run/podman/podman.sock"
          ENV_V3="CONTAINERUP_PODMAN_V3=1"
          ctnup_old=$(podman run -d --name containerup -e "CONTAINERUP_PASSWORD_HASH=${PWD_HASH}" -e "$ENV_V3" -v "$SOCKET_VOLUME" $IMAGE)
          echo $ctnup_old

          echo "Do upgrade"
          podman run --name containerup-updater -e "CONTAINERUP_UPDATE_IMAGE=$IMAGE" -e "CONTAINERUP_UPDATE_CURRENT_ID=${ctnup_old}" -e "$ENV_V3" -e "CONTAINER_UPDATE_RUN=1" -v "$SOCKET_VOLUME" $IMAGE

      - name: Test cleanup
        run: |
          podman rm -f containerup-updater containerup containerup-old

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: web/package-lock.json
      - name: Install npm dependencies
        run: |
          cd web
          npm install
      - name: Build project
        run: |
          export REACT_APP_CONTAINERUP_VERSION=${GITHUB_REF_NAME}
          export REACT_APP_CONTAINERUP_BUILD=$(date -u +%Y%m%d%H%M%S)
          export REACT_APP_CONTAINERUP_COMMIT=${GITHUB_SHA::7}
          echo BUILD=${REACT_APP_CONTAINERUP_BUILD}
          echo COMMIT=${REACT_APP_CONTAINERUP_COMMIT}
          cd web
          npm run build